### ISSUE TITLE
convert string to float

### ISSUE THREAD

**Issue by Feipian** [DarkTrick/python-video-silence-cutter#17]
When I want to use an example video to see if it works
but I face an exception

![image](https://github.com/user-attachments/assets/90e4cd8d-f42b-4800-8d9a-63193bf81f1b)

```
C:\Users\s1109\Desktop\Code\python-video-silence-cutter>python silence_cutter.py "C:\Users\s1109\Desktop\Code\python-video-silence-cutter\testdata\simple_video.mkv"  
detecting silences
Traceback (most recent call last):
  File "C:\Users\s1109\Desktop\Code\python-video-silence-cutter\silence_cutter.py", line 198, in <module>
    main()
  File "C:\Users\s1109\Desktop\Code\python-video-silence-cutter\silence_cutter.py", line 194, in main
    cut_silences (infile, outfile, dB)
  File "C:\Users\s1109\Desktop\Code\python-video-silence-cutter\silence_cutter.py", line 133, in cut_silences
    silences = findSilences (infile,dB)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s1109\Desktop\Code\python-video-silence-cutter\silence_cutter.py", line 46, in findSilences
    time_list.append (float(words[i+1]))
                      ^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '4.972062\\r'

```

**Comment by Feipian** [comment]
Resolved

**Comment by DarkTrick** [comment]
@Feipian  Can you share how you solved it ?
